### ISSUE TITLE
UnicodeDecodeError in Multibyte Enviroment

### ISSUE THREAD

**Issue by kirrytinyfang** [eliasdoehne/stellaris-dashboard#125] opened 2023-12-03 01:09 UTC
When using the dashboard in a Japanese environment, the following parsing error occurs.

Dashboard version: v6

```
2023-12-03 09:51:06,634 - stellarisdashboard.parsing.save_parser - INFO - Reading save file D:\Users\XXXXXX\Documents\Paradox Interactive\Stellaris\save games\_820700381\ironman.sav.
2023-12-03 09:51:07,460 - stellarisdashboard.parsing.save_parser - INFO - Parsed save file D:\Users\XXXXXX\Documents\Paradox Interactive\Stellaris\save games\_820700381\ironman.sav in 0.826 seconds.
2023-12-03 09:51:08,142 - stellarisdashboard.parsing.timeline - INFO - _820700381 2219.03.19 Processing Gamestate
2023-12-03 09:51:08,148 - stellarisdashboard.parsing.timeline - INFO - _820700381 2219.03.19 Gamestate for same date already exists in database. Aborting...
Traceback (most recent call last):
  File "stellarisdashboard\__main__.py", line 32, in <module>
  File "stellarisdashboard\__main__.py", line 24, in main
  File "stellarisdashboard\cli.py", line 84, in f_monitor_saves
  File "stellarisdashboard\dashboard_app\visualization_data.py", line 95, in get_current_execution_plot_data
  File "stellarisdashboard\dashboard_app\visualization_data.py", line 238, in update_with_new_gamestate
  File "stellarisdashboard\dashboard_app\visualization_data.py", line 301, in extract_data_from_gamestate
  File "stellarisdashboard\datamodel.py", line 678, in rendered_name
  File "stellarisdashboard\game_info.py", line 233, in render_name
  File "stellarisdashboard\game_info.py", line 245, in get_global_renderer
  File "stellarisdashboard\config.py", line 438, in localization_files
  File "stellarisdashboard\config.py", line 447, in <genexpr>
  File "stellarisdashboard\config.py", line 470, in _localization_file_matches_language
UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence
[5612] Failed to execute script '__main__' due to unhandled exception!
```

[_820700381.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/13537771/_820700381.zip)

**Comment by MichaelMakesGames** [comment] 2024-05-10 16:56
This is a duplicate of #127
We will track the work there.
Closing this issue.

**Closed by MichaelMakesGames** 2024-05-10 16:56 UTC
Labels: bug, duplicate
