### ISSUE TITLE
Missing folder

### ISSUE THREAD

**Issue by Tmktahu** [eliasdoehne/stellaris-dashboard#1] opened 2018-03-25 01:06 UTC
Just a heads up that it throws an error when it looks for the default $HOME/Documents/stellaristimeline/ folder because it hasn't been created yet.

Easy to work around....I just made the folder manually, but you'll prolly want a check in there or something.

**Comment by eliasdoehne** [comment] 2018-03-25 13:36
Good point, I think this issue is fixed, let me know if it still happens. Otherwise for now, the workaround is to create the folder manually, as you did.

**Comment by eliasdoehne** [comment] 2018-03-31 11:28
I will close the issue for now, because I cannot reproduce the problem with the most up to date version of the program. Let me know if this is still an issue in the current version, then I might update the instructions to let people know the workaround.

**Closed by eliasdoehne** 2018-03-31 11:28 UTC
