### ISSUE TITLE
cannot import name 'token_value_stream'

### ISSUE THREAD

**Issue by Tmktahu** [eliasdoehne/stellaris-dashboard#2] opened 2018-03-25 01:13 UTC
Upon running any command I get:
2018-03-24 18:12:12,500 - stellarisdashboard.save_parser - INFO - Cython extensions not available, using slow parser. Error message: "cannot import name 'token_value_stream'"

The program seems to continue and initialize without problems, but as expected it doesn't recognize save games or catch new ones.

**Comment by eliasdoehne** [comment] 2018-03-25 01:28
Yes this is probably an issue with the Cython extensions. They are currently not handled properly by the setup.py. Can you try re-installing the program with "pip install -e ." and see if it can then find the Cython extensions? (The compiled files in src/stellarisdashboard/cython_ext)

I have built a fallback solution that is much slower but I haven't tested it very extensively, so there are probably some bugs in there.

**Comment by Tmktahu** [comment] 2018-03-25 01:56
Unfortunately that didn't work. Same problem.

**Comment by eliasdoehne** [comment] 2018-03-25 02:03
hmm what platform are you using? (windows, mac, linux?)

**Comment by Tmktahu** [comment] 2018-03-25 02:25
Windows 10. It might have been a pathing problem because the error vanished once I hardcoded the path to token_value_stream.pyx
But, no dbs are made despite whether I make a new save after the normal stellarisdashboard command or run stellarisdashboardcli parse_saves.
Also fyi that Ctrl+C doesn't end the process....it just throws some crazy error.

**Comment by eliasdoehne** [comment] 2018-03-25 02:36
Yea almost certainly a problem with the paths, which will have to be fixed in the setup.py.
I assume that the Ctrl-C thing is probably related to the multiprocessing module in Windows, the problem is not there in Linux. 

So I assume that you are getting some output from the program like "Parsing save file xyz", and then it gets stuck?

I'm out for today, I will get back to you tomorrow.

**Comment by Tmktahu** [comment] 2018-03-25 02:37
Nope it doesn't even get that far. I get as far as:
2018-03-24 19:24:36,754 - stellarisdashboard.config - INFO - Reading config.ini file...
2018-03-24 19:24:37,090 - stellarisdashboard.save_parser - INFO - Initialized parsing worker pool with 5 threads.
And then it seems to quit out and I'm back to the prompt.

**Comment by Tmktahu** [comment] 2018-03-25 02:47
Also heads up that 5 threads is not the number I have set in the config.ini. Currently it's set to 3 threads.

**Comment by Tmktahu** [comment] 2018-03-25 03:18
Alright I fixed it. Hardcoding the path to the saves folder got it working. I wouldn't be surprised if it was the same problem with the path to the extension.

**Comment by eliasdoehne** [comment] 2018-03-25 12:48
Yes I think the problem with the config.ini file not being applied might be because if you install with "pip install .", it will copy all the python files to ".../python/lib/site-packages/stellarisdashboard", which is why the config.ini is not found. I have updated the instructions to install with "pip install -e ." as a quick workaround, maybe you could try re-installing with this method?

**Comment by eliasdoehne** [comment] 2018-03-31 11:25
I think this should be fixed with the current method of installation, as described in the updated readme. If there are any more issues, let me know!

**Closed by eliasdoehne** 2018-03-31 11:25 UTC
